/******************************************************************************
 *
 * Module: ULTRASONIC
 *
 * File Name: ultrasonic.c
 *
 * Description: Source file for the AVR ULTRASONIC driver
 *
 * Author: Mahmoud Tarek
 *
 *******************************************************************************/

#include "ultrasonic.h"
#include "common_macros.h" /* To use the macros like SET_BIT */
#include "icu.h"/*To send the configurations of edge and clock and initialize the icu*/
#include "gpio.h"/*To setup pin directions*/
#include <avr/io.h> /* To enable i-bit */
#include <util/delay.h>/*To delay the trigger signal*/

/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/

uint8 g_edgeCount = 0;
uint16 g_timeHigh = 0;

/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/
/*
 * Description : Function to initialize the ULTRASONIC driver
 * 	1. Initialize the ICU driver as required.
 * 	2. Setup the ICU call back function.
 * 	3. Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(void){
	/*Setup pin PB5 as trigger output for ultrasonic*/
	GPIO_setupPinDirection(PORTB_ID, PIN5_ID,PIN_OUTPUT);
	/*initialize the pin as low*/
	GPIO_writePin(PORTB_ID, PIN5_ID,LOGIC_LOW);
	/* Create configuration structure for ICU driver */
	Icu_ConfigType Icu_Config = {F_CPU_8,RISING};
	/* Enable Global Interrupt I-Bit */
	SREG |= (1<<7);
	/* Set the Call back function pointer in the ICU driver */
	Icu_setCallBack(Ultrasonic_edgeProcessing);
	/* Initialize the ICU driver */
	Icu_init(&Icu_Config);
}

/*
 * Description: Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void){
	/*
	 * Trigger pin activated
	 */
	GPIO_writePin(PORTB_ID, PIN5_ID,LOGIC_HIGH);
	_delay_us(12);/*minimum delay time for trigger signal from datasheet*/
	GPIO_writePin(PORTB_ID, PIN5_ID,LOGIC_LOW);
}

/*
 * Description: Send the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void){
	uint16 read_distance = 0;
	/*
	 * Trigger the ultrasonic pin to generate the echo pulses
	 */
	Ultrasonic_Trigger();
	while(1){
		if(g_edgeCount == 2)
		{
			g_edgeCount = 0;
			/* calculate the distance in cm */
			read_distance = 0.017*g_timeHigh+1;
			return read_distance;
		}
	}
}

/*
 * Description: This is the call back function called by the ICU driver
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void){
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		Icu_clearTimerValue();
		/* Detect falling edge */
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time value */
		g_timeHigh = Icu_getInputCaptureValue();
		/* Detect rising edge */
		Icu_setEdgeDetectionType(RISING);
	}
}
